### ISSUE TITLE
Update Composer.json to support drupal/bootstrap 3.23.0

### ISSUE THREAD

**Issue by xmacinfo** [open-data/gcweb_bootstrap#3]
Can you change support to Bootstrap to "3.23.0", or better yet, use "^3.23"?

This theme is the only blocker preventing our Drupal site to upgrade to Drupal 9 and moving to Boostrap 8.x-3.23 will fix the issue.

**Comment by ericbarrette** [comment]
I'm also interested in knowing when this is coming.  Is it planned to support Drupal 9 and when can we expect it?

Thanks!

**Comment by xmacinfo** [comment]
This is fixed, but the changes are not linked to this ticket.
